# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='轮播图')),
                ('bimage', models.ImageField(max_length=250, upload_to='static/images')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('cimage', models.ImageField(max_length=250, upload_to='static/images')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Furnishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=30, verbose_name='商品名称')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homeapp.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '家居',
                'verbose_name_plural': '家居',
            },
        ),
    ]
