# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntitle', models.CharField(max_length=50, verbose_name='动态标题')),
                ('nimage', models.ImageField(max_length=300, upload_to='static/images', verbose_name='动态封面图片')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('views', models.IntegerField(verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nctitle', models.CharField(max_length=50, verbose_name='分类标题')),
                ('ncimage', models.ImageField(max_length=300, upload_to='static/images', verbose_name='分类图片')),
                ('nccontent', models.CharField(max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name': '动态分类',
                'verbose_name_plural': '动态分类',
            },
        ),
        migrations.AddField(
            model_name='furnishing',
            name='Fimage',
            field=models.ImageField(default=django.utils.timezone.now, max_length=300, upload_to='static/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='ncategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homeapp.NewsCategory', verbose_name='分类'),
        ),
    ]
