# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20180622_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnishing',
            name='bgimage',
            field=models.ImageField(default=1, max_length=300, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
