# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_furnishing_bgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newcontent',
            field=models.CharField(default=1, max_length=2000, verbose_name='公司内容'),
            preserve_default=False,
        ),
    ]
