# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_news_newcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newcontent',
            field=models.CharField(max_length=2000, verbose_name='动态内容'),
        ),
    ]
