# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20180701_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingZhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='定制标题')),
                ('content', models.CharField(max_length=200, verbose_name='定制内容')),
            ],
        ),
    ]
