# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_dingzhi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutas',
            options={'verbose_name': '关于我们', 'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterModelOptions(
            name='demand',
            options={'verbose_name': '客户需求', 'verbose_name_plural': '客户需求'},
        ),
        migrations.AlterModelOptions(
            name='dingzhi',
            options={'verbose_name': '在线定制', 'verbose_name_plural': '在线定制'},
        ),
    ]
